### PR TITLE
set far future Expires header

### PR DESCRIPTION
**Pull request by srijken**
Make sure all content (except index.html because that's overruled) will
be cached.

### CODE REVIEW

**Comment by niemyjski** [comment]
Is there a way to not specify a year and just say cache for two years? Also I didn't see anywhere where it was filtering out the html files out of the exclude. I saw some place when I looked yesterday that they allow for specifying wildcards (*.css)

**Comment by niemyjski** [comment]
Where you able to specify a wildcard filter / generic future expiration?

**Comment by srijken** [comment]
I will take another look, it looks like a wildcard is not possible. Another option would be to place everything that should be cached with Far Future in a directory, and have a policy for that directory with <Location> or a web.config inside the directory.

**Comment by niemyjski** [comment]
That kind of stinks and would require a bit of work. It looks like we could cache everything and then do something like [this](http://stackoverflow.com/questions/2195266/how-to-configure-static-content-cache-per-folder-and-extension-in-iis7)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <location path="index.html">
        <system.webServer>
            <staticContent>
                <clientCache cacheControlMode="DisableCache" />
            </staticContent>
        </system.webServer>
    </location>
</configuration>
```

Could you give this a go? Also, if you haven't already could you please [sign our cla](http://www.clahub.com/agreements/exceptionless/Exceptionless)

**Comment by niemyjski** [comment]
I was just curious, if you apply just this change to our existing config, were you able to update the index.html config and have it not be cached?

**Comment by niemyjski** [comment]
Would this do the same thing? http://forums.iis.net/t/1179805.aspx

**Comment by niemyjski** [comment]
Can you please confirm that this won't cache the index.html file.

**Comment by niemyjski** [comment]
@srijken did you have anytime to look into this?

**Pull request closed without merging**
