### PR TITLE
Added sort indicator and ability to change sort

### PR DESCRIPTION
**Pull request by laughinggoose**
For #144. 

This is my first attempt at angular, so please let me know if there's a better way to accomplish what I did.

### CODE REVIEW

**Comment by niemyjski** [comment]
Looks great! I'm wondering if we should have a flag bool flag that defaults to showing this (hideSortByDate?) to not include the sort at all (previous behavior) on the passed in settings. For example, I don't think a sort would make sense on the most recent.. What are the thoughts on this? I guess it's still providing value and giving you the option even though you are doing the exact opposite of most recent.

**Comment by laughinggoose** [comment]
I think it would be okay to leave it without the flag. The behavior of the column doesn't change from previous versions unless you click on the header - and I'd hope that users wouldn't mind a caret suddenly appearing :)

I would actually love to have this sorting in our deployed version. Most recent is nice for reacting to things that are happening right now, but the reverse sort is helpful when cleaning up our list. I clean oldest -> newest so that I can prioritize bugs that slipped under the radar. Right now I'm just paging to the end, navigating, returning, paging some more, etc.

**Comment by niemyjski** [comment]
Thanks for the pr, I merged it into a branch and will do some testing on it before pushing it to master :)

**Comment by niemyjski** [comment]
It's going to master :)

**Comment by laughinggoose** [comment]
🚀 thanks!

**Pull request merged**
