### PR TITLE
Cleanup grunt configuration

### PR DESCRIPTION
**Pull request by boyomarinov**
+ switch from load-grunt-tasks to load-grunt-config
+ move config initializations from Gruntfile.js to separate files

### CODE REVIEW

**Comment by boyomarinov** [comment]
Hey, @niemyjski ,
It was easier for me to express the idea from [this issue](https://github.com/nikestep/grunt-html-angular-validate/issues/12) in code. Basically I have to admit that I mistook at first `load-grunt-tasks` for `load-grunt-config`, as I'm used to the second one, but actually the latter uses `load-grunt-tasks` underneath. The basic idea is that you want to keep your Gruntfile clean, so it's easier to maintain it. What `load-grunt-config` gives you is a way to separate neatly those tasks in files, which makes them very easy to review and support. 

About `htmlangular`:
 + the task works properly now : )
 + I see you have big enough code base, and W3C sets a timeout on their services after reaching certain limit of linting queries. I can suggest [htmlhint](https://www.npmjs.com/package/grunt-htmlhint), which I use in a big angular project of mine.

Cheers,
Boyan

**Comment by niemyjski** [comment]
Thank you for taking the time to do this.. It does look much better. Would you mind signing our cla so I can accept this commit: http://www.clahub.com/agreements/exceptionless/Exceptionless

**Comment by niemyjski** [comment]
Thank you for taking the time to do this.. It does look much better. Would you mind signing our cla so I can accept this commit: http://www.clahub.com/agreements/exceptionless/Exceptionless

**Comment by boyomarinov** [comment]
No problem. CLA has been signed :+1:

**Comment by niemyjski** [comment]
Thank you so much! I really like how it's a lot cleaner. If you have any other tips/feedback on things we can improve on please let us know!

**Pull request merged**
