### PR TITLE
 Added more translations and date time formatting for Chinese.

### PR DESCRIPTION
**Pull request by edwardmeng**
I have translated most of the words and sentences both in the html and js files. 
And localized the date time format. 
But several files have not been translated completely:
app.js
app\session\session.js
components\events\events-directive.tpl.html
components\organization-notifications\organization-notifications-directive.tpl.html
components\summary\templates\event-log-summary.tpl.html
components\summary\templates\event-error-summary.tpl.html
components\summary\templates\event-log-summary.tpl.html
components\summary\templates\stack-error-summary.tpl.html
components\summary\templates\stack-summary.tpl.html

And date time format in the following files:
app\organization\manage\invoices-directive.tpl.html
app\session\sessions-directive.tpl.html
app\stack\stack.tpl.html
components\events\events-directive.tpl.html
components\stacks\stacks-directive.tpl.html

Please take review and provide suggestions.

### CODE REVIEW

**Comment by Varorbc** [comment]
@niemyjski please review

**Comment by niemyjski** [comment]
Looks great, I’ll test out the changes and get this deployed but first can you revert the web.config changes? Also I was curious about using ng-bind-html in a few places instead of using {{‘text’ | translate}}

**Comment by edwardmeng** [comment]
@niemyjski Some of the translated content includes HTML markups. Just jusing {{‘text’ | translate}} will be encoded instead of displaying them as html markups. And I only know about using `ng-bind-html` can fix it.
Could you please introduce any more approach to deal with it?

**Comment by niemyjski** [comment]
Thanks for the pr. I'll review and get this deployed to production today or tomorrow.

**Comment by niemyjski** [comment]
@edwardmeng you can do `{{"text" | translate}}` inside of the html attributes / elements. This creates more work but makes it easier to change links. It's good as is :) Thanks for the PR and help.

**Pull request merged**
