### PR TITLE
Added Chinese language translations :)

### PR DESCRIPTION
**Pull request by niemyjski**
Thanks to an effort by @jianxuanbing, @Varorbc @edwardmeng! 

I just ensured we were sanitizing the validations to help prevent against XSS attacks. I also fixed some bugs with the dialogs. We are still missing some translations but I think this is a great start!

### CODE REVIEW

**Comment by Varorbc** [comment]
@niemyjski your chinese translations is ok

**Comment by Varorbc** [comment]
Do you have any other questions？@niemyjski

**Comment by niemyjski** [comment]
@Varorbc, @edwardmeng was making some more translation changes (missing) and we'll get this pushed real real real soon.

**Comment by niemyjski** [comment]
Currently the only thing blocking this commit from being included is I'm getting a translation js error thrown when viewing an event that has extended data. Can one of you look into this. I'm trying to figure out why I'm getting this error without much luck :\

 [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{'Additional Data' | translate}}] starting at [{'Additional Data' | translate}}].
http://errors.angularjs.org/1.6.9/$parse/syntax?p0=%7B&p1=invalid%20key&p2=2&p3=%7B%7B'Additional%20Data'%20%7C%20translate%7D%7D&p4=%7B'Additional%20Data'%20%7C%20translate%7D%7D

**Comment by niemyjski** [comment]
Thanks for the PR!!!!!!!!!

**Pull request merged**
